# Generated by Django 4.2.4 on 2023-08-06 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('core_count', models.PositiveIntegerField(default=0, verbose_name='Core Count')),
                ('core_clock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Core Clock')),
                ('boost_clock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Boost Clock')),
                ('tdp', models.PositiveIntegerField(verbose_name='TDP')),
                ('graphics', models.CharField(default='None', max_length=100, verbose_name='Integrated Graphics')),
                ('smt', models.BooleanField(default='False', verbose_name='Multithreading')),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('chipset', models.CharField(max_length=100)),
                ('memory', models.BigIntegerField()),
                ('core_clock', models.BigIntegerField(verbose_name='Core Clock')),
                ('boost_clock', models.BigIntegerField(verbose_name='Boost Clock')),
                ('color', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'gpu',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouritedPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.gpu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
