# Generated by Django 4.2.5 on 2023-10-31 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.pcase')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.gpu')),
                ('mboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.motherboard')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.psu')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.memory')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.storagedrive')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
