# Generated by Django 4.2.5 on 2023-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ready_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
