# Generated by Django 4.2.5 on 2023-09-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0002_alter_gpu_memory_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
