# Generated by Django 4.2.5 on 2023-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcase',
            name='external_525_bays',
        ),
        migrations.AddField(
            model_name='pcase',
            name='external_volume',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
