# Generated by Django 4.2.5 on 2023-10-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc_app', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.gpu')),
                ('mboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.motherboard')),
            ],
        ),
        migrations.CreateModel(
            name='CPUPivotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.DecimalField(decimal_places=0, max_digits=5)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
