# Generated by Django 4.2.4 on 2023-08-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0003_memory_alter_cpu_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cpu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gpu',
            table=None,
        ),
    ]
