# Generated by Django 4.2.4 on 2023-08-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0004_alter_cpu_table_alter_gpu_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
