# Generated by Django 4.2.5 on 2023-10-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0004_recommendedbuild_cpupivottable'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritedpc',
            name='mboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.motherboard'),
        ),
    ]
