# Generated by Django 4.2.5 on 2023-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0004_orderrating_cartitem_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
