# Generated by Django 4.2.5 on 2023-09-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0005_alter_orderrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='feedbacks',
        ),
    ]
