# Generated by Django 4.2.5 on 2023-10-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0006_profile_is_password_reset_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='mboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.motherboard'),
        ),
    ]
