# Generated by Django 4.2.4 on 2023-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0006_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('efficiency', models.CharField(max_length=50)),
                ('wattage', models.IntegerField()),
                ('modular', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
