# Generated by Django 4.2.4 on 2023-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0007_cartitem_mboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpupivottable',
            name='ratings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
