# Generated by Django 4.2.4 on 2023-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0007_psu'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('price_per_gb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('cache', models.IntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(max_length=50)),
                ('interface', models.CharField(max_length=50)),
            ],
        ),
    ]
