# Generated by Django 4.2.4 on 2023-08-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0008_storagedrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('psu', models.IntegerField()),
                ('side_panel', models.CharField(max_length=100)),
                ('external_525_bays', models.IntegerField()),
                ('internal_35_bays', models.IntegerField()),
            ],
        ),
    ]
