# Generated by Django 4.2.5 on 2023-10-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc_app', '0008_storagepivottable_rampivottable_psupivottable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.pcase'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='psu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.psu'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.memory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.storagedrive'),
        ),
        migrations.AddField(
            model_name='favouritedpc',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.pcase'),
        ),
        migrations.AddField(
            model_name='favouritedpc',
            name='psu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.psu'),
        ),
        migrations.AddField(
            model_name='favouritedpc',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.memory'),
        ),
        migrations.AddField(
            model_name='favouritedpc',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.storagedrive'),
        ),
        migrations.AlterField(
            model_name='favouritedpc',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu'),
        ),
        migrations.AlterField(
            model_name='favouritedpc',
            name='gpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.gpu'),
        ),
        migrations.AlterField(
            model_name='favouritedpc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
