# Generated by Django 4.2.4 on 2023-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0009_pcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritedpc',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
