# Generated by Django 4.2.5 on 2023-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0010_alter_cpupivottable_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcase',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='psu',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storagedrive',
            name='price',
            field=models.FloatField(),
        ),
    ]
