# Generated by Django 4.2.4 on 2023-08-29 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0010_favouritedpc_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
