# Generated by Django 4.2.4 on 2023-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0011_profile_created_at_profile_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
