# Generated by Django 4.2.4 on 2023-09-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0015_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='gpu_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.cpu'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='gpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.gpu'),
        ),
    ]
