# Generated by Django 4.2.4 on 2023-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0016_remove_cartitem_cpu_id_remove_cartitem_gpu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
