# Generated by Django 4.2.4 on 2023-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0017_cartitem_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='favouritedpc',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
