# Generated by Django 4.2.4 on 2023-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0018_alter_cartitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
