# Generated by Django 4.2.4 on 2023-09-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0019_alter_memory_price_alter_motherboard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='isShipped',
            field=models.BooleanField(default=False),
        ),
    ]
