# Generated by Django 4.2.4 on 2023-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0020_cartitem_isshipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
