# Generated by Django 4.2.4 on 2023-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('chipset', models.CharField(max_length=100)),
                ('memory', models.BigIntegerField()),
                ('core_clock', models.BigIntegerField(verbose_name='Core Clock')),
                ('boost_clock', models.BigIntegerField(verbose_name='Boost Clock')),
                ('color', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
