# Generated by Django 4.2.4 on 2023-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('price', models.FloatField()),
                ('core_count', models.PositiveIntegerField(default=0, verbose_name='Core Count')),
                ('core_clock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Core Clock')),
                ('boost_clock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Boost Clock')),
                ('tdp', models.PositiveIntegerField(verbose_name='TDP')),
                ('graphics', models.CharField(default='None', max_length=100, verbose_name='Integrated Graphics')),
                ('smt', models.BooleanField(default='False', verbose_name='Multithreading')),
                ('socket', models.CharField(default='Unknown', max_length=200)),
            ],
        ),
    ]
