# Generated by Django 4.2.5 on 2023-10-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_vendor', '0002_cpudata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPUData',
        ),
        migrations.DeleteModel(
            name='GPUData',
        ),
    ]
