# Generated by Django 4.2.4 on 2023-10-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_vendor', '0003_delete_cpudata_delete_gpudata'),
    ]

    operations = [
    ]
